### ISSUE TITLE
feature request: support data exports in german

### ISSUE THREAD

**Issue by markomi** [SwissClinicalTrialOrganisation/secuTrialR#10]
Currently, secuTrialR only works with data exports that have been made in English. We have a bunch of scripts that rely on data exports that have been made in German. Thus, for a bunch of projects, it is not possible to easily start using secuTrialR.
Because of this, I'd like to ask if you could add German language support for secuTrialR.
Let me know if I can help somehow.
Best,
M.

**Comment by aghaynes** [comment]
This predominantly affects the `load_export_options` function I think. This function parses the html export options file to get the necessary info.
Feel free to try and generalize. 
Can you attach an example export options file from such an export?

**Comment by markomi** [comment]
i'll send you a download link per email in a minute.

**Comment by PatrickRWright** [comment]
If we add these things we will need example data in the package though too. For testing etc.

**Comment by markomi** [comment]
Makes sense. Then I'll let you evaluate if you want to add this functionality. And if you do, I'll create an example data set. If you need example data for the evaluation process, let me know.

**Comment by aghaynes** [comment]
From my perspective, if there's a group of potential users that would need it, then we can do it, particularly if there's such a user willing to contribute (nudge nudge wink wink @markomi). 
If @PatrickRWright or I have to do the work, then it will have to wait until we have time... 

In either case, as @PatrickRWright  says, we need a reasonable example dataset for testing purposes (ideally with all variable types that we have special functions for - e.g. factors and dates). Inclusion of german might require changes in the date handling functions (specifically where the list of variables is filtered for dates - I would expect that to break)

**Comment by markomi** [comment]
Ah so one has to be careful what one wishes for ;) I'll check out if I can make a contribution.
And I'll try to find out if there are other people at our office who need german language support and will get back in touch.

**Comment by PatrickRWright** [comment]
@markomi
 
As far as I see changing the language affects the following files:

ExportOptions
items
cl

different language export are [here](https://github.com/SwissClinicalTrialOrganisation/secuTrialR/tree/master/inst/extdata).

**Comment by aghaynes** [comment]
if it changes any column names, I would suggest that we change them when reading the data in. 
I guess the biggest problem will be with items though - regex is used to identify variable types in multiple places.

**Comment by PatrickRWright** [comment]
A Vaild outcome may be to just support English and German.

**Comment by aghaynes** [comment]
Maybe there's a numeric code for variable types (e.g. 001 is text, 002 is 1dp numbers, 003 is 2 dp numbers)… an internal representation of the variable type that's shorter than the text and doesnt change by language. I cant think of anything off the top of my head, but who knows… then the language would only be an issue for the export options

**Comment by aghaynes** [comment]
Regex is used in multiple files, which probably depends on the language. I would suggest to add a new list to the export_options with the different regex statements necessary. This will save lots of if loops in the function definitions
e.g.
```
# in read_export_options
regex <- list()
if (language == "en"){
  regex$year <- "yyyy"
...
}
if (language == "de"){
  regex$year <- "jjjj"
...
}


# in functions
grepl(object$export_options$regex$year, x)

```

**Comment by aghaynes** [comment]
@PatrickRWright the italien and polish exports you added appear to be german...

**Comment by aghaynes** [comment]
Extra stuff we need to know to set the various objects in the export_options (how the options are translated in secutrial)
  1. short names
  2. rectangular data
  3. duplicate meta data

**Comment by aghaynes** [comment]
> 
> 
> @PatrickRWright the italien and polish exports you added appear to be german...

This might not quite be the case... It looks like they've only translated certain parts of the system into the other languages

**Comment by aghaynes** [comment]
covered in #63
