### ISSUE TITLE
If Project setup is not selected in Export Options the export will not load

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#103]
**Describe the bug**
If Project setup is not specified in Export Options the export will not load. A cryptic unhelpful error is returned.

**To Reproduce**
Export without Project setup and try `read_secuTrial()`.

**Expected behavior**
Return useful Error message or allow loading.

**Comment by aghaynes** [comment]
whats the error?

**Comment by PatrickRWright** [comment]
Error in \`[[<-.data.frame\`(\`*tmp*\`, id, value = character(0)) : replacement has 0 rows, data has 17
