### ISSUE TITLE
visit_structure

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#11]
1. allow for flexible visit plan
2. prepare test data with fixed visit plan

**Comment by aghaynes** [comment]
including the flexible visit plan will be difficult I think, because without the mnpvisno, there's no way to link the forms to the visit (that I know of currently)

**Comment by PatrickRWright** [comment]
@aghaynes is this likely something that you will/want to look into further? My feeling was that this may also not be technically possible. If you think it is not possible then we can maybe close this issue?

**Comment by aghaynes** [comment]
I haven't seen many projects without a fixed structure so I don't know what's possible and what not... According to what I currently (think I) know, it's not possible... so I guess the issue can be closed
