### ISSUE TITLE
diff_secuTrial example and tests with an actually changed CDMA

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#113]
**Is your feature request related to a problem? Please describe.**
Without an example where there are actual changes the output is not very informative.

**Describe the solution you'd like**

The below will not work because of an Error: "There is already a project with this name. Please enter a different one."
CTU05 Project setup can be exported, then imported to a new "pseudo-project" that looks exactly the same. Then changed can be made there and that setup can be exported as an example.

**Comment by markomi** [comment]
Thanks for looking into this Patrick. How about making a copy of the database under a different name, making an export, then making changes and exporting the new project version?

**Comment by PatrickRWright** [comment]
You are too clever for me. That is what I'll do.
