### ISSUE TITLE
factorize on same variable name in different forms with different data types

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#116]
**Describe the bug**
If there are two variables with the same name in two different forms, one of which can be factorized and one which can not (because it is e.g. a freetext variable), then the current implementation seems to "think" that the variable which can not be factorized can be.

This is not a big Problem but it triggers the "Unexpected" warning and adds a `.factor` column with all `NA` values. Also this is very unlikely to happen often or ever. Likely the database that I found this in has an implementation flaw and the freetext variable will be changed to a categorical one before it is set to productive mode. We should try and fix it anyway.

**To Reproduce**
Can't show this because it happened with a confidential data set.

**Expected behavior**
Don't try and factorize the variable which is not categorical.

**Comment by aghaynes** [comment]
I see the issue, but this is difficult because of the mismatch between the formnames in the metadata and the actual forms

**Comment by PatrickRWright** [comment]
You mean you have seen it in practice with your data too, or you understand what is happening?
