### ISSUE TITLE
Meeting Agenda 5th of December and TODO list after

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#118]
Meeting Agenda 5th of December (please extend if you have anything to add):  
- Figure out TODOs for release of a version 1.0 :heavy_check_mark:
  - warnings and notes must be cleared from the `R CMD check` :heavy_check_mark:
  - version increment test will have to be removed prior to CRAN submission (probably not since there is the option to `skip_on_cran()` [i.e.](https://github.com/SwissClinicalTrialOrganisation/secuTrialR/blob/master/tests/testthat/test-version_diff.R#L3) :heavy_check_mark:
- nomenclature throughout the package to retain consistency  :heavy_check_mark:
  - change referral to participant everywhere (no case, patient) :heavy_check_mark:
  - abbreviating of participant will remain pat :heavy_check_mark:
- publication of the package (CRAN, journal) :heavy_check_mark:
  - [JOSS](https://joss.theoj.org/) :heavy_check_mark:
- synchronisation strategy after first package publication ([github release](https://help.github.com/en/github/administering-a-repository/creating-releases) vs CRAN release) :heavy_check_mark:
  - CRAN is the stable version and github is dev :heavy_check_mark:
  - every version released on CRAN is to be tagged (release) on github (same version num of course) :heavy_check_mark:
- branch strategy after 1.0.0 (static master and dynamic dev?) :heavy_check_mark:
  - no dev branch :heavy_check_mark:
  - current version in master on github will always be the development version :heavy_check_mark:
- dissemination strategy  
  - twitter (DKF, CTU Bern, SCTO)
  - get in touch with iAS and ask them to promote it
  - present at iAS/secuTrial usermeeting
  - get in touch with personal contacts
  - internal CTU meetings
  - internal regulation/ruling (?)
  - blogs
  - email
  - publication
- dependencies :heavy_check_mark:
  - maybe we can have a look into which tidyverse components we needed and just mention the ones we need instead of loading the whole tidyverse (e.g. lubridate, dplyr...) :heavy_check_mark:
- package validation process
  - a template how to validate an R package has been developed [here](https://github.com/PatrickRWright/R_package_validation). This can be followed through for the secuTrialR package.
- who should we ask for user stories (CTU Bern, Basel... who else?) and should we provide a workflow/guide of what to test? :heavy_check_mark:
  - alan will ask in Bern :heavy_check_mark:
  - people interested in Basel have been recruited :heavy_check_mark:
  - ask steffi to spread the word in zürich :heavy_check_mark:
  - ask yann (zürich) :heavy_check_mark:
  - ask people from the user meeting iAS, stars, watchers :heavy_check_mark:
- vignette :heavy_check_mark:
  - a narrative walk through all functions :heavy_check_mark:
- shiny  :heavy_check_mark:
  - launch_dashboard() function (tracked as an issue) :heavy_check_mark:
- video demo
  - twotorials, chunk it up
  - dissemination youtube
- delete archived repositories :heavy_check_mark:
  - no objection to removing them :heavy_check_mark:
- commented code (what can be removed?) :heavy_check_mark:
  - patrick looks through and asks the others if he is not sure if something can be removed :heavy_check_mark:
- make it compulsory to create an issue with a concise description before adding a feature/fixing a bug  :heavy_check_mark:
- license GPL-2? Maybe rather MIT or more current GPL?  :heavy_check_mark:
  - change to MIT license  :heavy_check_mark:

**Comment by aghaynes** [comment]
What do you mean by user stories? What would we use them for?

**Comment by PatrickRWright** [comment]
User stories are basically just written experiences of people who have used the package and who are ideally not part of the development team. That way we will be made aware of problems which are very apparent to users but not to us because we are too deeply involved.

Long story short: Ask people to use the tool and give feedback (as specific as possible).
