### ISSUE TITLE
Compress date warnings

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#124]
**Is your feature request related to a problem? Please describe.**
Currently the warnings for incomplete dates can get a little out of hand and give the impression that a lot of things are out of order.

**Describe the solution you'd like**
Instead of pushing a warning for every variable, the warning message can likely be concatenated before it is pushed. This way there will be less warnings but the information is the same.

**Comment by aghaynes** [comment]
this would be somewhere near here I guess... https://github.com/SwissClinicalTrialOrganisation/secuTrialR/blob/39d90274e86b46cef00841cb037b48bd54d8bb99/R/dates_secuTrial.R#L61
