### ISSUE TITLE
Modularize the secuTrialR shiny dashboard

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#128]
**Is your feature request related to a problem? Please describe.**
Some of the code is quite repetitive, and should be condensed. (e.g. Download of SAS, STATA, SPSS data).

**Additional context**
https://shiny.rstudio.com/articles/modules.html

**Comment by markomi** [comment]
I'm starting to implement this. I'm planning to make 8 modules - one per dashboard tab.

**Comment by PatrickRWright** [comment]
Fantastic. Thank you @markomi
