### ISSUE TITLE
piping

### ISSUE THREAD

**Issue by aghaynes** [SwissClinicalTrialOrganisation/secuTrialR#13]
Check to see if piping works

**Comment by aghaynes** [comment]
it does! include in readme? @PatrickRWright what do you think?

**Comment by PatrickRWright** [comment]
do you have an example?

**Comment by aghaynes** [comment]
```
dat <- load_secuTrial_export(system.file("extdata", "s_export_CSV-xls_CTU05_longnames_sep_ref.zip",
                                         package = "secuTrialR"))
z <- dat %>% factorize_secuTrial() %>% dates_secuTrial()
```

**Comment by aghaynes** [comment]
`%>%` comes from `magrittr` (just in case you're not aware)

**Comment by PatrickRWright** [comment]
Yes, I just haven't been using it much (yet). Great that this works. I think its a good idea to have it in the readme.
