### ISSUE TITLE
searchable data tables for all data in the secuTrial export

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#131]
**Describe the solution you'd like**
Searchable table for each form. The structure initialize itsself and create a page similar to the "codebook" page which currently already exists. While at it also update the "codebook" tabs to a searchable table.

https://shiny.rstudio.com/gallery/datatables-options.html
https://www.htmlwidgets.org/showcase_datatables.html

**Comment by DrEspresso** [comment]
Do you mean to search for a variable name, e.g. "age", or to search for specific subsets, e.g. `age>40`

**Comment by PatrickRWright** [comment]
Ideally as versatile as possible (i.e. both), but I have to have a closer look into what's technically possible.

**Comment by markomi** [comment]
@PatrickRWright 
As discusssed, I have created the [secuTrialRshiny](https://github.com/SwissClinicalTrialOrganisation/secuTrialRshiny) package. All further development of and issue tracking for the shiny app should take place there.

I have referred to this issue in [secuTrialRshiny issue 4](https://github.com/SwissClinicalTrialOrganisation/secuTrialRshiny/issues/4) and am thus closing #131.
