### ISSUE TITLE
Function to merge a set of given forms to a single data frame

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#132]
**Is your feature request related to a problem? Please describe.**
Sometimes we may need to supply a subset of the data all merged into one table.

**Describe the solution you'd like**
A function which takes a vector of form names and creates a single merged data frame.

**Describe alternatives you've considered**
The alternative is not having such a function in secuTrialR and implementing the merge manually whenever you need it.

@markomi @aghaynes thoughts?

**Comment by DrEspresso** [comment]
Interesting thought, but probably the specific needs each time differ too much to construct a generally useful function. (I.e. inner, outer, left join, subforms, casenodes,...)

**Comment by PatrickRWright** [comment]
At the DM meeting the idea came up to create the rectangular table from the non rectangular export within `secuTrialR` and compare it to the rectangular table exported in the ExportSearchTool. This could also be used to check the technical validity of some of the R package's functionalities.

**Comment by DrEspresso** [comment]
In this case, I think the title of the issue is slightly misleading, as the rectangular export of secuTrial is a very specific form of a "single data frame".

**Comment by PatrickRWright** [comment]
Maybe a paragraph on data/form merging in the vignette will suffice.
