### ISSUE TITLE
Improved error handling when path to file in `read_secuTrial()` does not exist

### ISSUE THREAD

**Issue by DrEspresso** [SwissClinicalTrialOrganisation/secuTrialR#137]
**Is your feature request related to a problem? Please describe.**
When trying to import a file that doesn't exist, the error message
> Input to read_secuTrial() appears to be incompatible. Have you exported CSV format?

is too generic. Additionally, the code continues to execute and some more error messages are thrown:
>label_secuTrial() failed. Proceeding without labelling.
factorize_secuTrial() failed. Proceeding without factorization.
dates_secuTrial() failed. Proceeding without date parsing.
read_secuTrial() failed.

**Describe the solution you'd like**
`read_secuTrial()` should check at first if the file to be read does exist. If not, a clear error message should be shown and the execution should be stopped.

**Comment by PatrickRWright** [comment]
Thank you for the valid request @DrEspresso 

I will include a `file.exists()` in the beginning of `read_secuTrial()` and `read_secuTrial_raw()`.

**Comment by DrEspresso** [comment]
Cool, thank you both @PatrickRWright @markomi :+1:
