### ISSUE TITLE
funny "usage" lines in secuTrialdata.Rd

### ISSUE THREAD

**Issue by gillesdutilh** [SwissClinicalTrialOrganisation/secuTrialR#139]
There are two funny lines in the "usage" of secuTrialdata.Rd:

print(x)
plot(x)

**Comment by PatrickRWright** [comment]
hey @gillesdutilh 

These lines come from the custom `print()` and `plot()` methods for the secuTrialdata object.

The relevant lines are [this](https://github.com/SwissClinicalTrialOrganisation/secuTrialR/blob/master/R/read_secuTrial_raw.R#L116) and [this](https://github.com/SwissClinicalTrialOrganisation/secuTrialR/blob/master/R/read_secuTrial_raw.R#L144).

**Comment by PatrickRWright** [comment]
I wonder if we should remove the generic `plot()` since we are not exporting it anyway. For the `print()` we should maybe change the x to something more descriptive.

**Comment by gillesdutilh** [comment]
If print just works without further arguments, you do not need to describe in the help. You could add both generic function descriptions under "see also".
