### ISSUE TITLE
Suggestions for return_random_participants

### ISSUE THREAD

**Issue by DrEspresso** [SwissClinicalTrialOrganisation/secuTrialR#151]
**Is your feature request related to a problem? Please describe.**
The function does not check whether a centre in <code>centers</code> exists.
The function does not accept <code>percent=1</code> (maybe useful for consistency checks)
The help page does not explain how the percentage of participants is rounded to integers.

**Describe the solution you'd like**
A warning should be shown if an element of <code>centers</code> is not an element of <code>...$ctr</code>

The allowed range of values for <code>percent</code> should include 0 and 1.

The help page should be extended. 
There is also one typo:
> percantage

**Comment by PatrickRWright** [comment]
@DrEspresso it would be good to have this implemented by late February just to give a timeline. Can you do that?
