### ISSUE TITLE
Include in vignette

### ISSUE THREAD

**Issue by suvi-subra** [SwissClinicalTrialOrganisation/secuTrialR#156]
The following error message  could be better explained in the vigenette. Thank you.

**_"Warning messages:
1: In label_secuTrial.secuTrialdata(d) :
  some variable names appear to be duplicated - labels attribute may be longer that 1"_**

**Comment by suvi-subra** [comment]
Another warning:

**_2: In dates_secuTrial.data.frame(tmp, datevars, timevars, dateformat,  :
#                                    Not all dates were converted for
#                                  variable: 'discharge_date'
#                                  in form: 'nrl08visit_data'
#                                  This is likely due to incomplete date entries._**

**Comment by aghaynes** [comment]
> Another warning:
> 
> **_2: In dates_secuTrial.data.frame(tmp, datevars, timevars, dateformat, : Not all dates were converted for variable: 'discharge_date' in form: 'nrl08visit_data' This is likely due to incomplete date entries._**

The bottom of page 6 of the vignette covers this. Is that not sufficient?

**Comment by PatrickRWright** [comment]
@aghaynes that was my fault. I forgot that I had entered this in the vignette and asked @suvi-subra to add this to the issue. Maybe we could also add a specific example though?

**Comment by suvi-subra** [comment]
Thank you Patrick. I just read it and it seems helpful.

**Comment by PatrickRWright** [comment]
@aghaynes we could add a paragraph in the vignette on Errors and Warnings?

**Comment by aghaynes** [comment]
> @aghaynes we could add a paragraph in the vignette on Errors and Warnings?

That's not a bad idea... you have time?

**Comment by PatrickRWright** [comment]
I can do it, yes.
