### ISSUE TITLE
recommended export options

### ISSUE THREAD

**Issue by aghaynes** [SwissClinicalTrialOrganisation/secuTrialR#17]
Add a screen shot with recommended export options

**Comment by PatrickRWright** [comment]
Do we have agreement on what those should be?

**Comment by aghaynes** [comment]
I dont think so, but I would suggest something like this
![image](https://user-images.githubusercontent.com/6594028/57907323-61e2a800-787d-11e9-8e7a-cfec6a75613c.png)
I'm not sure about the parts in yellow though. They can be useful sometimes
Shorten names I'm not so concerned about, as secuTrialR handles that either way.
Character Encoding might be an issue - UTF-8 perhaps?
Maybe it would be good to mention the date-time defaults, as that will avoid introducing NAs and the user then has control over what it is entered if something is missing, rather than us...

**Comment by PatrickRWright** [comment]
I think UTF-8 is good. Once we have agreed on the recommended set we should maybe also add an FYI warning when the export is being loaded and some things differ.

**Comment by aghaynes** [comment]
Sure. Most of that can then go into the export options function I suppose...
Did you agree with my suggestion then or would you go a different route?

**Comment by PatrickRWright** [comment]
I just had another look at this and think "Queries and Comments", "SDV", "Missing Values" and "Audit trail" can all be ticked too.

**Comment by aghaynes** [comment]
as recommended? I'm not so convinced. They're very specific and not useful for a whole lot (normally). The audit trail gives particular difficulties with dates, factors etc as you have to assume that any form beginning with at is an audit trail, although there may be hacks to get around that. It also slows down exports dramatically (particularly for large databases).
Is missing value the MIV file? Might that be another way to do this missing data thing you're currently doing with that other validation export....?
I have no idea what SDV (source data verification) would be useful for.
