### ISSUE TITLE
Hidden visits

### ISSUE THREAD

**Issue by aghaynes** [SwissClinicalTrialOrganisation/secuTrialR#177]
It has just come to my attention that visits/observations can be hidden in SecuTrial (as well as items senso #172). To the best of my knowledge we do not handle them at all at the moment. Maybe we should do something about them, or have a function to remove them perhaps? 
I'm currently waiting on info as to how to identify these visits/observations...

**Comment by PatrickRWright** [comment]
So hidden variables can be identified with the `return_hidden_items()` function. If hidden data is part of the export that is also tracked in the `export_options$hidden_fields`.

I think the same logic holds for forms but I didn't implement a function to return them.

**Comment by aghaynes** [comment]
Having played around a little with a DM, it looks like the "show hidden fields" button controls both hidden variables and visits/observations. Maybe it's worth producing a warning if that option is checked (the data probably shouldn't be used...)

**Comment by PatrickRWright** [comment]
Probably `check_export_options()` is the right place.
