### ISSUE TITLE
Handle different versions of R packages

### ISSUE THREAD

**Issue by witchi** [SwissClinicalTrialOrganisation/secuTrialR#22]
How you handle the different versions of additional packages in R? Our statisticians can update the packages and R/RStudio, but often our own scripts will only work with a special version of R and special versions of the used packages, which we refer on the scripts. Do you have a solution to specify the package versions (and dependencies) and the R version within the script?

It is not possible to validate the scripts without such a mechanism. I'm interesting in a general solution for that problem, which all statisticians can use without a lot of individual changes.

**Comment by aghaynes** [comment]
This question isn't specifically to do with secuTrialR, so there are better forums for such questions (e.g. StackOverflow, twitter using the #rstats tag or one of the r users mailing lists). Never the less,  I'll give you some suggestions...

The best thing that I know of is to print `sessionInfo()` for any given analysis. That will tell what versions of packages were used for the analysis (assuming all used packages are attached). 

For packages in CRAN, the older versions are normally archived, so they are accessible long after they've been updated.
For github, I suppose you'd have to hope that the package version is updated regularly enough (which we do not yet do) or use tags to identify the current version. However, you cannot tell from the sessionInfo whether a package is from CRAN or github (or any other repo)

With packages, it's relatively simple...you can just refer to a given package version in the depends field of the DESCRIPTION file.
