### ISSUE TITLE
read_secuTrial() not loading data downloaded in correct format

### ISSUE THREAD

**Issue by suvi-subra** [SwissClinicalTrialOrganisation/secuTrialR#237]
I downloaded an export from secuTrial with the recommended options selected. However, read_secuTrial() is producing the following error:

Input to read_secuTrial() appears to be incompatible. It should be in CSV format and not be rectangular.
label_secuTrial() failed. Proceeding without labelling.
factorize_secuTrial() failed. Proceeding without factorization.
dates_secuTrial() failed. Proceeding without date parsing.
read_secuTrial() failed._

**Comment by aghaynes** [comment]
discussions with @suvi-subra have suggested that this was probably due to long names.
