### ISSUE TITLE
Form labels and "form table names"

### ISSUE THREAD

**Issue by gillesdutilh** [SwissClinicalTrialOrganisation/secuTrialR#239]
When I read secuTrial data, I always have some difficulty getting to understand the structure and finding the forms I need. THe function visit_structure() is somewhat useful (in combination with plot()), but one problem is still that I then do not know which form table names belong to each form name (I would refer to these form names that you see in visit_structure as "form labels")

I would like to be able to see at a glance or which form names belong to these form labels.

One option would be to add this to the output of visit structure. Another option would be to have a helper function like the one below, that translates form labels to form names.

`
form_name = function(x, label){ unique(x$forms$formtablename[x$form$formname %in% label])}
`

But maybe more elegant would be to automatically export a form dictionary, either as a named vector, or as a little data.frame with columns "form_name" and "form_label"

**Comment by aghaynes** [comment]
I remember why we didn't do much in this direction now... it gets difficult because the metadata isn't consistent with the names of the data frames, and it's not trivial to link them... it's particularly problematic where the short names option has been used... the mnpp1059 part in the example below is system and project specific if i remember correctly.

![grafik](https://user-images.githubusercontent.com/6594028/152153178-7548c817-7630-47ec-b470-d9dd373a3e7b.png)

Also, the subforms don't always have specific datasets...

If something like this is OK
![grafik](https://user-images.githubusercontent.com/6594028/152153563-c82f10a8-d9b1-4072-a0b4-c420c1ac5894.png)
which fits to this
![grafik](https://user-images.githubusercontent.com/6594028/152153588-b5de5ba4-d266-4408-a20e-a2868a46d24f.png)
it's easy, but the `formtablename` doesn't match to the names of the data (see `names(x)` above). We could generate a warning where short names are used perhaps...?

**Comment by aghaynes** [comment]
Is this useful? If so, I can add it...

```r
st_dictionary <- function(x){
  
  tmp <- merge(unique(x[[x$export_options$meta_names$items]][, c("fgid", "ffcolname", "itemtype", "fflabel", "unit")]), 
             unique(x[[x$export_options$meta_names$questions]][, c("fgid", "formtablename", "formname")]), 
             all.x = TRUE, by = "fgid")
  dict <- merge(unique(y[, c("formtablename", "formname", "ffcolname", "itemtype", "fflabel", "unit")]), 
             unique(x[[x$export_options$meta_names$forms]][, c("formtablename", "formname", "formfamily")]),  
             by = c("formtablename", "formname"))
  return(dict)
}
```
an extra to do would be to modify the formtablename afterwards, but as I say, thats not so simple due to system specific stuff...

**Comment by gillesdutilh** [comment]
I do not completely understand. There is a unique mapping between formname and formtablename, right? In that case, you can also give out a dictionary of formtablename and formname, right?

**Comment by aghaynes** [comment]
the function above gives a dictionary of which variables are on which form... something slightly different to what you were asking, I know, but probably useful nonetheless...

And no (or at least not always) is there a unique mapping between formtablename and formname. Here's an example of a dataset I happen to working on at the moment. It looks like the forms were renamed at some point in the trial and secuTrial retains both names in the metadata.
![grafik](https://user-images.githubusercontent.com/6594028/154426136-4d6300fc-a479-4850-a01a-32a68ce42b24.png)

I can provide a function that spits out something like in the pic above, but getting unique values would require assumptions (e.g. use the first label, which might be the old name)...

Another thing to consider, which I either forgot about or never knew - not all forms are related to a given visit... baseline type things. Thus, these do not appear in the output from `visit_structure` at all...

**Comment by gillesdutilh** [comment]
OK, I see the problem. So, each formtablename can be associated with multiple formnames. Not the other way around: each form name has one unique formatablename. Would it, at least for visit structure (and the plot of that) not be good to have an option showing which formtablename belongs to each formname?

**Comment by aghaynes** [comment]
think i found a solution... I can include formtablename in the output from visit_structure. then you can print the object, as opposed to plotting it...
![grafik](https://user-images.githubusercontent.com/6594028/154655904-d2d5fee6-5a03-4e25-a88e-7a7f072e7dde.png)

can you install it with `remotes::install_github("aghaynes/secuTrialR-1")` and give it a try?
