### ISSUE TITLE
Order of appearnce of seperator in head,  quotes and order of conditions matter when importing tables

### ISSUE THREAD

**Issue by miljukov-o** [SwissClinicalTrialOrganisation/secuTrialR#240]
I had trouble reading in a SecuTrial export because some csv-files contained textfields with quotes (") in it. Which lead to incomplete table imports without any error or warning. I saw by coincidence, that some tables had unexpectedly less rows (patients) in the imported data frames and started searching for the cause.

The root cause lies in the correct specification of the parameters for the read.table() function.

I tried several combinations with different seperators and quotes and escapes for the read.table() function when configuring the Export Formats. The solution that worked for me error-free was tab as separator and @ as quotes. Unfortunately, the read.table() function doesn't recognize them automatically and needs them specified. 

Also, if I configured e.g. " ; " as seperator and " ' " as quote, the function would read the table incorrect because of the order of the conditions here.

So it would be great being able to specify the parameters as user. Thank you very much.

https://github.com/SwissClinicalTrialOrganisation/secuTrialR/blob/fb551f60dee4a2e3fa6e769e128b82bdfc741f9e/R/read_export_options.R#L175

**Comment by aghaynes** [comment]
Thanks for highlighting that... i think it should be possible to accommodate that. 

Parsing the html is error prone unfortunately...

You need then the `sep`, `quote` and `allowEscapes` arguments? I think that I can see a way forward to implement that...

**Comment by miljukov-o** [comment]
Yes, the arguments would be great.

**Comment by aghaynes** [comment]
I think I have a solution for this, but I dont have any suitable data to test it on...  can you give me a couple of examples of the strings causing problems and the export options you use so that I can try to create a small export with the same issue for testing?

**Comment by aghaynes** [comment]
I implemented something for this, can you install it with `remotes::install_github("aghaynes/secuTrialR-1")` and give it a try?

**Comment by miljukov-o** [comment]
Hi, thank you very much. 

I've tried the new version. From initially 9 erroneous files 6 remained erroneous.
The first free text field that I could find, after which the error occured:

In SecuTrial Export:

> "aaa:  \"	bbb. ccc, ddd.  \"	eee. fff.  \"	ggg.  \"	hhh.  \"	iii, jjj."

Same field copied from DataCapture:

> aaa: " bbb. ccc, ddd. " eee. fff. ggg. " hhh. " iii. " jjj.

**Comment by aghaynes** [comment]
So there are still errors, but less of them... any indication of whats causing the problem now?

The text you copied is normal. R needs to escape the quotation marks so that it doesnt treat them as multiple chunks of text. It uses backslashes for this purpose. It should be OK when you print or use it in a table or something.

That warning message doesn't look like it's a problem. I'll have a look and see if we open connections without closing them again though.
