### ISSUE TITLE
function names: load -> read

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#25]
@gillesdutilh suggested that read may be more appropriate than load for our function names. 

e.g.:
load_export_table.R -> read_export_table.R

**Comment by aghaynes** [comment]
i dont know about appropriate, but it would certainly be more consistent with the rest of the R...

**Comment by PatrickRWright** [comment]
I think that was pretty much exactly how the suggestion was originally worded. I would say we make the changes. Basically some simple "search and replace". I can handle that maybe later this week. Any objections from your side?

**Comment by aghaynes** [comment]
not at all

**Comment by gillesdutilh** [comment]
Oops, sorry for not getting back to this!
Gilles

Op ma 20 mei 2019 om 14:45 schreef Alan Haynes <notifications@github.com>:
