### ISSUE TITLE
Rename data.frames to custom names in as.data.frame()

### ISSUE THREAD

**Issue by DrEspresso** [SwissClinicalTrialOrganisation/secuTrialR#250]
**Is your feature request related to a problem? Please describe.**
Using the `data.frames` option in `as.data.frame()`, one can select a subset of secuTrial tables to be turned into data.frames. It is only possible to rename data.frames using the `regex ` and `rep` options in `as.data.frame()`. There is no option to rename data.frames into custom names.

**Describe the solution you'd like**
If the option `data.frames` is used with a _named_ vector, the data frames from the `secuTrialdata` object should be turned into data frames whose names are given by `names(data.frames)`.

**Comment by aghaynes** [comment]
thanks for implementing!
