### ISSUE TITLE
Reading \" in free text variables

### ISSUE THREAD

**Issue by DrEspresso** [SwissClinicalTrialOrganisation/secuTrialR#261]
**Describe the bug**
When exporting to CSV, in free text variables secuTrial adds backslashes to escape the character used as enclosure (default `"`). secuTrialR currently ignores the backslash and splits free text containing the enclosure character to multiple columns, thereby shifting also all following lines. This leads to a cascade of problems and wrong data.

Also, secuTrialR currently only reads exports with enclosure `"`, while secuTrial allows to choose other enclosure characters (e.g. `'`) in the CSV export options.

**To Reproduce**
1. Save a free text containing `"` in a form
2. Create a new export
3. Read the new export

**Expected behavior**
1. secuTrialR should be compatible will all enclosure characters supported by secuTrial.
2. secuTrialR should understand escaped enclosure characters

**Additional context**
Implementing 1. would potentially allow a workaround using a new export with an enclosure character that has not been stored in any free text item. But in theory one could run out of options, as all of them could be used in free text items of the same project.

**Comment by aghaynes** [comment]
closed by #262
