### ISSUE TITLE
Update technical drawing of the package architecture

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#27]
Current:
https://github.com/SwissClinicalTrialOrganisation/secuTrialR/blob/master/inst/extdata/secuTrialR.png

Following may be useful:
https://cran.r-project.org/web/packages/Gmisc/vignettes/Grid-based_flowcharts.html
https://cran.r-project.org/web/packages/CodeDepends/vignettes/intro.html

**Comment by aghaynes** [comment]
See PR #35
