### ISSUE TITLE
factorize_secuTrial does not factorize lookup tables

### ISSUE THREAD

**Issue by a-lenz** [SwissClinicalTrialOrganisation/secuTrialR#50]
If reference values are stored in a lookup table (e.g. lmnppXX instead of emnppXX or mnppXX), they are not assigned to a particular form. In the cl form, the form is then missing in cl$column, and the variables don't get factorized.

**Comment by aghaynes** [comment]
Need to use the items and forms tables probably and do something specific for the lookup tables i suppose
