### ISSUE TITLE
Export to other formats?

### ISSUE THREAD

**Issue by aghaynes** [SwissClinicalTrialOrganisation/secuTrialR#51]
From the SCTO DM meeting
EXE or Shiny app to export to other stats program formats?

**Comment by aghaynes** [comment]
#52 supports exporting to SPSS, STATA, and SAS

Shiny app could be a further development

**Comment by aghaynes** [comment]
See also #57 (XPT files)

**Comment by PatrickRWright** [comment]
#96 is a first attempt at a shiny deployment. I have since created a shiny dashboard which is quite a bit more fancy and which I will likely PR soon. I also contains deployment of an option to convert and save the data to e.g. Stata readable format.

**Comment by aghaynes** [comment]
@PatrickRWright can this be closed or should we keep it open for the XPT issue?

**Comment by PatrickRWright** [comment]
Keep it open for now, but I have an eye on it.

**Comment by PatrickRWright** [comment]
I will close this after updating the shiny dashboard where I will deploy an option to download all translations.
