### ISSUE TITLE
Duplicate form meta data into all tables

### ISSUE THREAD

**Issue by nicoleb7** [SwissClinicalTrialOrganisation/secuTrialR#54]
This export option must trigger an exception because it prevents proper loading.

**Comment by aghaynes** [comment]
Can you show the code and error message? Your message is currently too cryptic for me to do anything with. Is sharing the data possible? (I see that you're at Basel, so maybe you can give the export to @PatrickRWright...)

**Comment by PatrickRWright** [comment]
We were looking at it together and the error was somewhat cryptic. I assume if you select the export option "Duplicate form meta data into all tables" something breaks. My suggestion is to capture this option in the export options and make a check which then throws an informative error.

This is also related to:
#17

**Comment by nicoleb7** [comment]
Dear both


if "Duplicate form meta data into all tables" was selected on export, the error is:



> read_secuTrial("exports/p_export_CSV-xls_UKB08_20190613-100702.zip")

Error in `[[<-.data.frame`(`*tmp*`, id, value = integer(0)) :
  replacement has 0 rows, data has 78
>


otherwise the read_secuTrial() works very nice - altough the automated date recognition (which I know from the former version) does not work in my case:


----------------------

'data.frame':    78 obs. of  210 variables:
 $ pat_id                     : Factor w/ 78 levels "LOOP-BS-001",..: 1 2 3 4 5 6 7 8 9 10 ...
 $ visit_name                 : chr  "Baseline" "Baseline" "Baseline" "Baseline" ...
 $ centre                     : Factor w/ 2 levels "Basel (LOOP)",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ mnppid                     : int  1955 1979 2036 2038 2040 2042 2055 2057 2058 2077 ...
 $ mnpdocid                   : int  2 21 41 45 50 54 82 86 89 122 ...
 $ mnplastedit                : Factor w/ 78 levels "2019-03-20 15:05:16",..: 71 74 56 40 54 42 3 1 45 58 ...
 $ mnpptnid                   : int  801 801 801 801 801 801 801 801 801 801 ...
 $ mnpvisid                   : int  9151 9151 9151 9151 9151 9151 9151 9151 9151 9151 ...
 $ mnpcvpid                   : int  1 21 61 63 66 67 81 84 85 101 ...
 $ mnpvisno                   : int  1 1 1 1 1 1 1 1 1 1 ...
 $ mnpvispdt                  : Factor w/ 41 levels "2019-03-07","2019-03-08",..: 1 2 4 4 4 4 5 5 5 6 ...
 $ mnpvisfdt                  : Factor w/ 78 levels "2019-03-07 09:35:49",..: 1 2 3 4 5 6 7 8 9 10 ...
....


I found the automatic date recognition a very useful feature ...


Thanks and best regards


Nicole


Nicole Bruni, PhD | Datenmanagerin

Universität Basel | Departement Klinische Forschung | Clinical Trial Unit

c/o Universitätsspital Basel | Spitalstrasse 12 | CH-4031 Basel

Tel. +41 61 556 54 08 | Erreichbar Mo, Di, Do

________________________________
Von: Patrick R. Wright <notifications@github.com>
Gesendet: Donnerstag, 13. Juni 2019 14:49:17
An: SwissClinicalTrialOrganisation/secuTrialR
Cc: Bruni Nicole; Author
Betreff: Re: [SwissClinicalTrialOrganisation/secuTrialR] Duplicate form meta data into all tables (#54)


We were looking at it together and the error was somewhat cryptic. I assume if you select the export option "Duplicate form meta data into all tables" something breaks. My suggestion is to capture this option in the export options and make a check which then throws an informative error.

This is also related to:
#17<https://github.com/SwissClinicalTrialOrganisation/secuTrialR/issues/17>

**Comment by aghaynes** [comment]
Regarding the automatic data recognition stuff... it doesnt do the system variables (at the moment), but the date variables within the data itself should be interpreted (i.e., mnpvisfdate wont be, but dob should be)

**Comment by nicoleb7** [comment]
deleted my message due to data in there not to be shown publicly...

**Comment by PatrickRWright** [comment]
fixed in #58
