### ISSUE TITLE
Allow for xpt files to be created.

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#57]
**Is your feature request related to a problem? Please describe.**
When writing to xpt the variable names are truncated.

**Describe the solution you'd like**
Allow for xpt files to be created.

**Additional context**
Currently the lines of code in write_secutrial.R regarding xpt files are commented. Also the tests regarding xpt files have been deactivated for now.

**Comment by aghaynes** [comment]
this appears to be primarily a bug with haven

**Comment by PatrickRWright** [comment]
the loading or the writing?

**Comment by aghaynes** [comment]
no idea... you looked into it ;) my comment was just a little additional documentation :) Without SAS, it's difficult to tell

**Comment by PatrickRWright** [comment]
Ah ok. I thought you had some new information.
