### ISSUE TITLE
Missing date formatting with export option "Duplicate form meta data..."

### ISSUE THREAD

**Issue by markomi** [SwissClinicalTrialOrganisation/secuTrialR#62]
@aghaynes @PatrickRWright 
**Describe the bug**
Date strings are not formatted as Dates in secuTrial exports where the Export option "Duplicate form meta data into all tables" has been selected.

**To Reproduce**
1. Load a secuTrial export with "Duplicate form meta data into all tables"
2. Check any table with a Date column
3. Columns that contain dates are coded as int

**Expected behavior**
Date strings are transformed into a Date format. These transformed variables are found in a separate column that ends with ".Date".

**Additional context**
It seems that the merge() in dates_secuTrial.secuTrialdata() function on line 42 is not executed correctly because of duplicated metadata columns.

**Comment by PatrickRWright** [comment]
Thank you @markomi for picking this up. @aghaynes can you fix this?

**Comment by aghaynes** [comment]
this is probably the same as was fixed in #58 (which fixed #54). will look into it
