### ISSUE TITLE
If Add-ID is not selected in Export Options the export will not load

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#67]
I will fix this myself.

**Describe the bug**
If Included data:  Patient identifier: Add-ID is not selected reading of an export will not work. This is correct but a sensible error message needs to be thrown [here](https://github.com/SwissClinicalTrialOrganisation/secuTrialR/blob/master/R/read_secuTrial_export.R#L71).

**To Reproduce**
The file is in the data archive of this package.
```
read_secuTrial_export("s_export_CSV-xls_CTU05_shortnames_sep_ref_no_addid.zip")
```

**Comment by aghaynes** [comment]
I disagree. We shouldn't force people to have the AID in their datasets, IMO. We can determine whether the AID is there in the export_options and then set the parameter to read_table appropriately... that would be better.

**Comment by PatrickRWright** [comment]
I'm not sure how much downstream processing this will require, but I'll have a look.
