### ISSUE TITLE
Factor levels for lookup table related fields is not correct

### ISSUE THREAD

**Issue by markomi** [SwissClinicalTrialOrganisation/secuTrialR#71]
**Describe the bug**
Factor levels for lookup table related fields contain levels of not just the field in question, but also of associated fields.

**To Reproduce**
1. Go to a secuTrialR import of a secuTrial repetition subform that contains a drop-down field, with a dependend lookup table and a second-level lookup table.
2. Go to the emnp repetition subform, then to the column containing the drop-down field.
3. Explore the factor levels
4. Factor levels contain all possible values of the drop-down field, the dependent lookup table, and the second-level lookup table.

**Expected behavior**
Each secuTrialR imported table column associated with a lookup table, will contain only the factor levels associated with that lookup table.

**Screenshots**
n.a.

**Additional context**
Hope I've described it well enough.

**Comment by PatrickRWright** [comment]
Example:
Lets say you have a lookuptable with level 1 selections A and B. If you select A then the level 2 allows for selection of 1, 2 and 3. If you select B then you can select 7, 8, 9 on level 2. If you look at the factorization of level 2 then you get 1, 2, 3, 7, 8, 9 while you likely only want 1, 2, 3 if you selected A on level 1 and vice versa for B.

**Comment by PatrickRWright** [comment]
Upon closer inspection I think this cannot be remedied since the information to subdivide the groups is not in the export data.

**Comment by PatrickRWright** [comment]
This was explicitly addressed in #73. It can not be changed since the information is, to the best of our knowledge, not in the export data.
