### ISSUE TITLE
Supply more complex CDMA and example data

### ISSUE THREAD

**Issue by PatrickRWright** [SwissClinicalTrialOrganisation/secuTrialR#9]
The current example data (bone mineral denisty - bmd) is too small to allow rigorous testing of all functionalities. Thus a more complex eCRF/CDMA with data should be implemented and included into the package data. The data will likely be randomly generated from an appropriate range.

Types to be included:
- several differing visits
- casenodes (including SAE)
- repetitions
- scores
- a catalogue (e.g. medication)
- rules
- checkboxes
- radiobuttons
- all datatypes (e.g. dates, integers, doubles, freetext)
- randomization
- treatment arms (suggested by @Inessakraft )

**Comment by aghaynes** [comment]
related to #2

**Comment by PatrickRWright** [comment]
https://github.com/SwissClinicalTrialOrganisation/secuTrialR/tree/master/inst/extdata
