### ISSUE TITLE
Start documenting changes in NEWS

### ISSUE THREAD

**Issue by aghaynes** [SwissClinicalTrialOrganisation/secuTrialR#92]
**Is your feature request related to a problem? Please describe.**
It's probably good to start a NEWS file to document the changes between versions

**Describe the solution you'd like**
See e.g. https://github.com/tidyverse/ggplot2/blob/master/NEWS

**Comment by PatrickRWright** [comment]
Good idea. It crossed my mind too recently. Can you start with a PR and a NEWS which basically says that we are now publishing a NEWS file starting version 0.4.17?
